# Link settings
baseurl: ""
url: "https://ehsanmaminejad.github.io"
permalink: /:year/:month/:day/:title/


# Build settings
markdown: kramdown
#theme: minima  # Note: We'll remove this when implementing custom themes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination settings
paginate: 6
paginate_path: "/blog/page/:num"

# Language settings
languages: ["en", "fa"]
default_lang: "en"
exclude_from_localizations: ["assets", "images", "css", "js", "fonts"]

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true

sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: "assets/images"
      type: "posts"
    values:
      layout: "post"
      author: "Ehsan Maminejad"
      comments: true
  - scope:
      path: "_posts/fa"
      type: "posts"
    values:
      lang: "fa"
      direction: "rtl"
  - scope:
      path: "_posts/en"
      type: "posts"
    values:
      lang: "en"
      direction: "ltr"

# Markdown settings
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter: rouge

# Development settings
watch: true
safe: true

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENSE
  - CNAME