#-------------------------------
# Site Settings
logo: logo.svg

#-------------------------------
# Author Settings
author:
  name: Ehsan Maminejad
  image: 01.jpg
  say-hello: Hello, I'm <strong>Ehsan Maminejad</strong> and welcome to my site.
  bio: I’m a data scientist and engineer who loves solving real-world problems with machine learning, AI, and data.
    Skilled in building scalable solutions and always exploring new ways to optimize and innovate.

# Contact links
github: https://github.com/ehsanmnd
linkedin: https://www.linkedin.com/in/ehsanmaminejad
    # Add more social links as needed

#-------------------------------
# Blog Settings
blog:
  title: Blog
  description: My latest thoughts and stories

#-------------------------------
# Contact Settings
contact:
  email: ehsan.maminejad@gmail.com
  description: Get in touch with me

#-------------------------------
# Analytics Settings
google-analytics: G-18WKJXFHXS

#-------------------------------
# Build Settings
disqus-identifier: Echius # Add your shortname for Disqus Comment